controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
